In [173]:
import pandas as pd
import numpy as np

In [174]:
df = pd.read_csv("fear_greed_index.csv")
df

       timestamp  value classification        date
0     1517463000     30           Fear  2018-02-01
1     1517549400     15   Extreme Fear  2018-02-02
2     1517635800     40           Fear  2018-02-03
3     1517722200     24   Extreme Fear  2018-02-04
4     1517808600     11   Extreme Fear  2018-02-05
...          ...    ...            ...         ...
2639  1745818200     54        Neutral  2025-04-28
2640  1745904600     60          Greed  2025-04-29
2641  1745991000     56          Greed  2025-04-30
2642  1746077400     53        Neutral  2025-05-01
2643  1746163800     67          Greed  2025-05-02

[2644 rows x 4 columns]

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB

In [176]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2639    False
2640    False
2641    False
2642    False
2643    False
Length: 2644, dtype: bool

In [177]:
df1= pd.read_csv("historical_data.csv")
df1

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,382.20,420.80,SELL,25-04-2025 15:35,7546.600000,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,88803313862,False,0.042080,1.990000e+14,1.750000e+12
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,2124.10,2338.63,SELL,25-04-2025 15:35,7164.400000,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,88803313862,False,0.233863,9.260000e+14,1.750000e+12
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,423.40,466.16,SELL,25-04-2025 15:35,5040.300000,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,88803313862,False,0.046616,6.930000e+14,1.750000e+12
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,3599.80,3963.38,SELL,25-04-2025 15:35,4616.900000,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,88803313862,False,0.396337,4.180000e+14,1.750000e+12
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,1017.10,1119.83,SELL,25-04-2025 15:35,1017.100000,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,88803313862,False,0.111982,3.270000e+14,1.750000e+12

In [178]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [179]:
df1.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
211219    False
211220    False
211221    False
211222    False
211223    False
Length: 211224, dtype: bool

In [180]:
df1["Timestamp"] = pd.to_numeric(df1['Timestamp'], errors='coerce')

In [181]:
df1["Timestamp"]

0         1.730000e+12
1         1.730000e+12
2         1.730000e+12
3         1.730000e+12
4         1.730000e+12
              ...
211219    1.750000e+12
211220    1.750000e+12
211221    1.750000e+12
211222    1.750000e+12
211223    1.750000e+12
Name: Timestamp, Length: 211224, dtype: float64

In [182]:
df1["Timestamp"].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
211219    False
211220    False
211221    False
211222    False
211223    False
Name: Timestamp, Length: 211224, dtype: bool

In [183]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [184]:
df1["Timestamp"] = pd.to_datetime(df1['Timestamp'], unit='ms').dt.date

In [185]:
df1["Timestamp"]

0         2024-10-27
1         2024-10-27
2         2024-10-27
3         2024-10-27
4         2024-10-27
             ...
211219    2025-06-15
211220    2025-06-15
211221    2025-06-15
211222    2025-06-15
211223    2025-06-15
Name: Timestamp, Length: 211224, dtype: object

In [186]:
df1

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,2024-10-27
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,2024-10-27
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,2024-10-27
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,2024-10-27
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,2024-10-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,382.20,420.80,SELL,25-04-2025 15:35,7546.600000,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,88803313862,False,0.042080,1.990000e+14,2025-06-15
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,2124.10,2338.63,SELL,25-04-2025 15:35,7164.400000,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,88803313862,False,0.233863,9.260000e+14,2025-06-15
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,423.40,466.16,SELL,25-04-2025 15:35,5040.300000,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,88803313862,False,0.046616,6.930000e+14,2025-06-15
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,3599.80,3963.38,SELL,25-04-2025 15:35,4616.900000,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,88803313862,False,0.396337,4.180000e+14,2025-06-15
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,1017.10,1119.83,SELL,25-04-2025 15:35,1017.100000,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,88803313862,False,0.111982,3.270000e+14,2025-06-15

In [187]:
df1['Timestamp'] = pd.to_datetime(df1['Timestamp'])
df1_daily = df1.groupby(df1['Timestamp'].dt.date).agg({
    'Closed PnL':'sum',
    'Order ID': 'count'
}).reset_index()

df1_daily.rename(columns={'Timestamp':'Date'},
                inplace = True)
df1_daily

         Date    Closed PnL  Order ID
0  2023-03-28  0.000000e+00         3
1  2023-11-14  1.555034e+02      1045
2  2024-03-09  1.769655e+05      6962
3  2024-07-03  1.587424e+05      7141
4  2024-10-27  3.189461e+06     35241
5  2025-02-19  6.699925e+06    133871
6  2025-06-15  7.170935e+04     26961

In [188]:
df_daily = df.groupby('date').agg({
    'classification':'first'
}).reset_index()

df_daily.rename(columns={'date':'Date'},
                inplace = True)
df_daily

            Date classification
0     2018-02-01           Fear
1     2018-02-02   Extreme Fear
2     2018-02-03           Fear
3     2018-02-04   Extreme Fear
4     2018-02-05   Extreme Fear
...          ...            ...
2639  2025-04-28        Neutral
2640  2025-04-29          Greed
2641  2025-04-30          Greed
2642  2025-05-01        Neutral
2643  2025-05-02          Greed

[2644 rows x 2 columns]

In [189]:
df1_daily['Date'] = pd.to_datetime(df1_daily['Date'])
df_daily['Date'] = pd.to_datetime(df_daily['Date'])

In [190]:
merged = pd.merge(df1_daily, df_daily, on='Date', how='inner')

In [191]:
merged

        Date    Closed PnL  Order ID classification
0 2023-03-28  0.000000e+00         3          Greed
1 2023-11-14  1.555034e+02      1045          Greed
2 2024-03-09  1.769655e+05      6962  Extreme Greed
3 2024-07-03  1.587424e+05      7141        Neutral
4 2024-10-27  3.189461e+06     35241          Greed
5 2025-02-19  6.699925e+06    133871           Fear

In [192]:
merged['Date'] = pd.to_datetime(merged['Date']).dt.date
win_rate_daily['Date'] = pd.to_datetime(win_rate_daily['Date']).dt.date

In [193]:
df1['win'] = df1['Closed PnL']>0

win_rate_daily = df1.groupby(df1['Timestamp'].dt.date)['win'].mean().reset_index()
win_rate_daily.rename(columns={'Timestamp':'Date'}, inplace = True)

In [194]:
win_rate_daily

         Date       win
0  2023-03-28  0.000000
1  2023-11-14  0.274641
2  2024-03-09  0.490089
3  2024-07-03  0.317182
4  2024-10-27  0.451605
5  2025-02-19  0.415146
6  2025-06-15  0.349171

In [195]:
merged = merged.merge(win_rate_daily, on='Date')

In [196]:
merged

         Date    Closed PnL  Order ID classification       win
0  2023-03-28  0.000000e+00         3          Greed  0.000000
1  2023-11-14  1.555034e+02      1045          Greed  0.274641
2  2024-03-09  1.769655e+05      6962  Extreme Greed  0.490089
3  2024-07-03  1.587424e+05      7141        Neutral  0.317182
4  2024-10-27  3.189461e+06     35241          Greed  0.451605
5  2025-02-19  6.699925e+06    133871           Fear  0.415146

In [197]:
merged.groupby('classification')['win'].mean()

classification
Extreme Greed    0.490089
Fear             0.415146
Greed            0.242082
Neutral          0.317182
Name: win, dtype: float64

In [198]:
merged.groupby('classification')['Closed PnL'].mean()

classification
Extreme Greed    1.769655e+05
Fear             6.699925e+06
Greed            1.063206e+06
Neutral          1.587424e+05
Name: Closed PnL, dtype: float64

In [200]:
#Average Trade Size
df1['trade_size'] = abs(df1['Closed PnL'])

avg_trade_size = df1.groupby(df1['Timestamp'].dt.date)['trade_size'].mean().reset_index()

avg_trade_size.rename(columns={'Timestamp':'Date'}, inplace = True)
avg_trade_size

         Date  trade_size
0  2023-03-28    0.000000
1  2023-11-14   29.770178
2  2024-03-09   48.333821
3  2024-07-03   68.343278
4  2024-10-27  118.692369
5  2025-02-19   70.186245
6  2025-06-15   65.284779

In [211]:
#Leverage Distribution
df1.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp', 'win', 'trade_size'],
      dtype='object')

In [212]:
#Long/Short Ratio
df1['Direction'].value_counts(normalize=True)

Direction
Open Long                    0.236218
Close Long                   0.230457
Open Short                   0.188146
Close Short                  0.170497
Sell                         0.094222
Buy                          0.079139
Spot Dust Conversion         0.000672
Short > Long                 0.000331
Long > Short                 0.000270
Auto-Deleveraging            0.000038
Liquidated Isolated Short    0.000005
Settlement                   0.000005
Name: proportion, dtype: float64

In [204]:
#Fear Vs. Greed performance compare
merged.groupby('classification')[['Closed PnL','win']].mean()

                  Closed PnL       win
classification
Extreme Greed   1.769655e+05  0.490089
Fear            6.699925e+06  0.415146
Greed           1.063206e+06  0.242082
Neutral         1.587424e+05  0.317182

In [207]:
#Segments
#High Vs. Low Traders

merged['trader_type'] = merged['Order ID'].apply(lambda x: 'High' if x>50000 else 'Low')

merged.groupby('trader_type')['Closed PnL'].mean()

trader_type
High    6.699925e+06
Low     7.050649e+05
Name: Closed PnL, dtype: float64

In [209]:
#Consisent Vs. Inconsistent
merged['consistency'] = merged['win'].apply(lambda x: 'Consistent' if x>0.4 else 'Inconsistent')
merged['consistency']

0    Inconsistent
1    Inconsistent
2      Consistent
3    Inconsistent
4      Consistent
5      Consistent
Name: consistency, dtype: object